version: "3.3"

services:
  frontend:
    ports:
      - 3000:3000
    build:
      context: packages/frontend
      dockerfile: Dockerfile
    volumes:
      - ./packages/frontend/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
  backend:
    ports:
      - 3333:3333
    build:
      context: packages/backend
      dockerfile: Dockerfile
    volumes:
      - ./packages/backend/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
